openapi: 3.0.0
info:
  title: Easyappz Telegram Payments API
  version: 1.0.0
  description: API for managing settings, payments, stats and bot control.
servers:
  - url: /api
paths:
  /settings:
    get:
      summary: Get current settings
      responses:
        '200':
          description: Settings document
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Setting'
    put:
      summary: Create or update settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                telegramBotToken:
                  type: string
                telegramProviderToken:
                  type: string
                title:
                  type: string
                description:
                  type: string
                currency:
                  type: string
                  example: RUB
                amount:
                  type: number
                  description: Amount in minor units (e.g., kopeks)
                successMessage:
                  type: string
                  example: 'Payment received: {amount} {currency}. Thank you!'
      responses:
        '200':
          description: Saved settings
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Setting'
  /payments:
    get:
      summary: List payments
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [pending, succeeded, expired, failed]
        - in: query
          name: limit
          schema:
            type: integer
            default: 50
        - in: query
          name: skip
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of payments
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Payment'
  /stats:
    get:
      summary: Get payments statistics
      responses:
        '200':
          description: Stats by status
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      total:
                        type: integer
                      byStatus:
                        type: object
                        properties:
                          pending:
                            type: integer
                          succeeded:
                            type: integer
                          expired:
                            type: integer
                          failed:
                            type: integer
                      generatedAt:
                        type: string
                        format: date-time
  /bot/restart:
    post:
      summary: Restart bot with current settings
      responses:
        '200':
          description: Bot restart result
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      restarted:
                        type: boolean
                      hasTokens:
                        type: boolean
components:
  schemas:
    Setting:
      type: object
      properties:
        _id:
          type: string
        telegramBotToken:
          type: string
        telegramProviderToken:
          type: string
        title:
          type: string
        description:
          type: string
        currency:
          type: string
        amount:
          type: number
          description: Amount in minor units
        successMessage:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Payment:
      type: object
      properties:
        _id:
          type: string
        chatId:
          type: integer
        userId:
          type: integer
        payload:
          type: string
        status:
          type: string
          enum: [pending, succeeded, expired, failed]
        title:
          type: string
        description:
          type: string
        currency:
          type: string
        amount:
          type: number
          description: Amount in minor units
        invoiceMessageId:
          type: integer
        providerPaymentChargeId:
          type: string
        telegramPaymentChargeId:
          type: string
        expiresAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
