openapi: 3.0.0
info:
  title: Easyappz Telegram Payments API
  version: 1.0.0
  description: API for managing settings, payments, stats and bot control.
servers:
  - url: /api
paths:
  /settings:
    get:
      summary: Get current settings
      responses:
        '200':
          description: Settings document
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Setting'
    put:
      summary: Create or update settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                telegramBotToken:
                  type: string
                telegramProviderToken:
                  type: string
                title:
                  type: string
                  maxLength: 32
                  description: |
                    Invoice title. Max 32 characters. Will also be used as price item label.
                    Allowed characters: latin/cyrillic letters, digits, space, hyphen, dot, comma, colon, underscore.
                    New lines are not allowed and will be replaced by spaces.
                description:
                  type: string
                currency:
                  type: string
                  example: RUB
                  description: Three uppercase letters ISO-4217 code (e.g., RUB, USD, EUR). Must be exactly 3 uppercase letters.
                  pattern: '^[A-Z]{3}$'
                amount:
                  type: integer
                  minimum: 1
                  description: Amount in minor units (e.g., kopeks). Must be a positive integer (> 0).
                successMessage:
                  type: string
                  description: |
                    Supports placeholders {amount} (major units) and {currency}. Example: "Payment received: {amount} {currency}. Thank you!"
      responses:
        '200':
          description: Saved settings
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Setting'
  /payments:
    get:
      summary: List payments
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [pending, succeeded, expired, failed]
        - in: query
          name: limit
          schema:
            type: integer
            default: 50
        - in: query
          name: skip
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of payments
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Payment'
  /stats:
    get:
      summary: Get payments statistics
      responses:
        '200':
          description: Stats by status
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      total:
                        type: integer
                      byStatus:
                        type: object
                        properties:
                          pending:
                            type: integer
                          succeeded:
                            type: integer
                          expired:
                            type: integer
                          failed:
                            type: integer
                      generatedAt:
                        type: string
                        format: date-time
  /bot/restart:
    post:
      summary: Restart bot with current settings
      responses:
        '200':
          description: Bot restart result
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      restarted:
                        type: boolean
                      hasTokens:
                        type: boolean
components:
  schemas:
    Setting:
      type: object
      properties:
        _id:
          type: string
        telegramBotToken:
          type: string
        telegramProviderToken:
          type: string
        title:
          type: string
          maxLength: 32
          description: |
            Max 32 characters. Used as invoice title and price item label. No line breaks. Allowed: latin/cyrillic letters, digits, space, hyphen, dot, comma, colon, underscore.
        description:
          type: string
        currency:
          type: string
          description: Three uppercase letters ISO-4217 code (e.g., RUB, USD, EUR). Must be exactly 3 uppercase letters.
          pattern: '^[A-Z]{3}$'
        amount:
          type: integer
          minimum: 1
          description: Amount in minor units (positive integer > 0).
        successMessage:
          type: string
          description: Supports placeholders {amount} (major units) and {currency}.
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Payment:
      type: object
      properties:
        _id:
          type: string
        chatId:
          type: integer
        userId:
          type: integer
        payload:
          type: string
        status:
          type: string
          enum: [pending, succeeded, expired, failed]
        title:
          type: string
        description:
          type: string
        currency:
          type: string
        amount:
          type: integer
          description: Amount in minor units
        invoiceMessageId:
          type: integer
        providerPaymentChargeId:
          type: string
        telegramPaymentChargeId:
          type: string
        expiresAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
